# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: DataNovum.DiskSaver
PackageVersion: 1.1.0
InstallerType: portable
Commands:
  - disksaver
ReleaseDate: 2026-10-04
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/novumdata0-collab/disksaver/releases/download/v1.1.0/DiskSaver.exe
    InstallerSha256: 774BFF54C42F625157CEA9FB2C50400A8C597AC59894FAA08C923FD758821199
ManifestType: installer
ManifestVersion: 1.12.0
